### ISSUE TITLE
Identical Wallet Addresses Across Blockchains without Merging Coins

### ISSUE THREAD

**Issue by cherubtorch** [bitcoin-sv/bitcoin-sv#172]
I am the proud owner of a single Bitcoin SV.  No more and no less.  I would like to own a matching Bitcoin ABC and Bitcoin Cash address that I can hold in the same wallet or in separate wallets without merging the coins so that if I chose to spend from the bitcoins or add to them it will only add or subtract from the appropriate Blockchain’s balance and not from all 3.

**Comment by cherubtorch** [comment]
Update: Definitional issue, could issue in fact be not an issue?

**Comment by Danconnolly** [comment]
I dont advise re-using an address for privacy reasons. Re-using the same address links payments together, even across chains.

BCH uses a different address display format. I'm not sure where they are with that, whether they still support the old format, because I don't really keep up with that chain.

But at a technical level, the keys behind the addresses are the same, so it is possible to hold BSV and BCH in the same address, even if the addresses may look different (due to the different address display formats). If you hold BSV and BCH that has been acquired after the time when they split (November 2018), then it is very unlikely that any transactions from one will affect the other.

Lastly, this is really a wallet question. You'd be better off asking this of a wallet developer.
