### ISSUE TITLE
bitcoind auto-kills its processes

### ISSUE THREAD

**Issue by pouyiouk** [bitcoin-sv/bitcoin-sv#194]
I have started a new node. It synchronised the whole chain from the start up to date `2015-08-03 17:28:48` and block `best=00000000000000000a7178ebb54e6f405d2d694beba40c32edfe3fd6fb77f4e6 height=368267 version=0x00000003` and then out of sudden kills itself. (Console output: killed)

After restarting the software, it confirms the last six blocks as a usual and then prints out the message log output below and starts resyncing from the best hash chain once again.

### Block confirmation log output:
`2021-01-13 08:59:12 [bitcoin-main] LoadBlockFileInfo: last block file info: CBlockFileInfo(blocks=6, size=2134030, heights=0...365835, time=2009-01-03...2015-07-18)`
`2021-01-13 08:59:12 [bitcoin-main] Checking all blk files are present...`
`2021-01-13 08:59:12 [bitcoin-main] LoadBlockIndexDB: transaction index enabled`
`2021-01-13 08:59:12 [bitcoin-main] Initializing databases...`
`2021-01-13 08:59:12 [bitcoin-main] Loaded best chain: hashBestChain=000000000000008daec3f7c9d863723cc0736b3a8ded7573cc974e3424039a0f height=184493 date=2012-06-14 12:35:45 progress=0.007678`
`2021-01-13 08:59:12 [bitcoin-main] init message: Rewinding blocks...`
`2021-01-13 08:59:14 [bitcoin-main] init message: Verifying blocks...`
`2021-01-13 08:59:14 [bitcoin-main] Verifying last 6 blocks at level 3`
`2021-01-13 08:59:14 [bitcoin-main] [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].`
`2021-01-13 08:59:28 [bitcoin-main] No coin database inconsistencies in last 7 blocks (2670 transactions)`
`2021-01-13 08:59:30 [bitcoin-main] NotifySafeModeLevelChange: Warning: Found chain at least ~6 blocks longer than our best chain.
Still waiting for block data.`
`2021-01-13 08:59:30 [bitcoin-main] CheckSafeModeParametersForAllForksOnStartup: global safe mode state restored to level 1 in 1926ms
` 

### What version of bitcoin-sv are you using?
bitcoin-sv-1.0.6

### Machine specs:
- OS: Ubuntu 20.04.1 LTS
- CPU: i7-7820X 
- RAM: 64GB

### bitcoin.conf file
`excessiveblocksize=0`
`maxstackmemoryusageconsensus=0`
`maxmempool=8000 #8G`
`dbcache=8192 #8G`
`maxconnections=80`
`port=9333`
`rpcport=9332`
`txindex=1 `
`#rpc settings`
`rpcworkqueue=600`
`rpcthreads=128`
`rpcuser=user`
`rpcpassword=password`
`proxy=127.0.0.1:9050` 
`printtoconsole=1`
`server=1`
`#debugexclude to ignore set log items, can be used to keep log file a bit cleaner`
`debugexclude=libevent`
`debugexclude=leveldb`
`debugexclude=zmq`
`debugexclude=txnsrc`
`debugexclude=net`

It is kinda funny the way it handles the issue. It reached a point where the software doesn't know what to do and automatically kills the process. how am I supposed to progress, what are my options?

**Comment by gopinathev** [comment]
Hi

Can you add the output of the following grep
`grep 'oom\|bitcoin-main' /var/log/syslog*`

Also, can you confirm whether the node has completed the Initial Block Download after restarting the software?

**Comment by pouyiouk** [comment]
@gopinathev I did some more research, it was a mempool and cache problem. I removed the two commands from bitcoin.conf file and it works past that point normally, syncing with the network. I used the example .conf file from the BSV website. 

maxmempool=8000 #8G
dbcache=8192 #8G

Issue is resolved but still I haven't understood why the process gets killed. I haven't looked at the source code yet but is there a failsafe that when cache or mempool allocated storage is exceeded or reaches its max the software quits?

**Comment by pouyiouk** [comment]
@gopinathev 
Version: bitcoin-sv-1.0.7 beta
Error repeated itself with default settings at 09/12/2020 transactions and progress 95%

Log output error after running the command you supplied me with:

- `/var/log/syslog:Jan 17 20:08:16 ubuntu kernel: [95858.660022] txnvalidator invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0`
- `/var/log/syslog:Jan 17 20:08:16 ubuntu kernel: [95858.661636]  oom_kill_process.cold+0xb/0x10`
- `/var/log/syslog:Jan 17 20:08:16 ubuntu kernel: [95858.666048] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name`
- `/var/log/syslog:Jan 17 20:08:16 ubuntu kernel: [95858.666335] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=main,pid=3502,uid=1000`
- `/var/log/syslog:Jan 17 20:08:16 ubuntu kernel: [95858.667098] Out of memory: Killed process 3502 (main) total-vm:11606368kB, anon-rss:4790248kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:12492kB oom_score_adj:0`
- `/var/log/syslog:Jan 17 20:08:16 ubuntu kernel: [95859.233190] oom_reaper: reaped process 3502 (main), now anon-rss:28kB, file-rss:0kB, shmem-rss:0kB
`

**Comment by shyrwall** [comment]
Just means you don't have enough RAM.

**Comment by conceptrat** [comment]
> Issue is resolved but still I haven't understood why the process gets killed. I haven't looked at the source code yet but is there a failsafe that when cache or mempool allocated storage is exceeded or reaches its max the software quits?

I'm not seeing any more replies to this post.  Did you figure this out in the end?

To my not so experienced kernel programming grey matter, it looks a lot like you're now hitting a memory limit as OOM (in kernel) is killing the process "`Out of memory: Killed process 3502 (main)`".  Perhaps a very large block (caused by several large transactions) as BitcoinSV allows for almost unlimited block sizes now right?  One of the pitfalls of increasing or removing the block size limitations.  Moores law may eventually catch up there.

Strangely the memory usage for this program is ~11GB virtual memory and ~4GB for resident memory (rss - resident set size) for a total of ~15GB.  This may not be showing the memory used by other processes/allocations spawned from within the program.  Given that you have 64GB of RAM on this box this is all a bit surprising.  Although some of the available real memory could be taken up with other processes that you haven't mentioned in your post (try looking in `/var/log/messages` or using `dmesg` for the full memory stats at the time of the OOM killed the process).  Or it could be memory fragmentation and the process can't get a large enough block of memory allocated.  Or even a memory leak in the process somewhere.

Another possibility could be if you're perhaps using cgroups and a rule there is restricting the amount of memory available to the process, hence OOM killing it?  That "main" process is running as a normal user (uid=1000) it might be restricted.  Try typing "`ulimit -a`" in the shell before running the main process and look a the "memory" limits. 

Check the OOM score for the process with "`cat /proc/$PID/oom_score`".  A score of 0 means that the process is exempt from the OOM killer.  If you want to disable OOM for the process then you can use "`echo -17 > /proc/$PID/oom_adj`".  Of course doing this means that this process won't get killed, can take more memory etc and other processes, perhaps more important ones, will potentially get killed.  You could instead try "`echo -16 > /proc/$PID/oom_adj`", which significantly reduces the chances of the process getting killed by OOM.

This is all conjecture on my part as, like I said earlier, I'm no kernel programmer.  What I will say is that I've struck issues with MariaDB, Apache, PHP and a few other programs/services getting killed by the OOM.  Most often it was because the container I was running in had restrictions on the amount of memory various processes were allowed to consume.

"We are all Satoshi" 😼

**Comment by CassClark** [comment]
Hi @conceptrat  to cover this off, as I see you haven't received a response, as you pointed out the syslog shows the error "Out of memory: Killed process 3502 (main)".  So essentially the node was setup with too little memory, when it ran out, the OS killed it.
