### ISSUE TITLE
alter minminingtxfee without node restart

### ISSUE THREAD

**Issue by mboyd1** [bitcoin-sv/bitcoin-sv#299]
As a miner I want to be able to adjust `minminingtxfee` on-the-fly, such that my next `getminingcandidate` call will pull in or drop transactions from the block template according to the changes made to fee levels.

Current practice is altering the value in bitcoin.conf or command-line, requiring a full restart of the node which is undesirable.

**Comment by mickmight** [comment]
Thanks for this suggestion. I have added this to the backlog and the team will have a look at this in due course. 

For info, please describe how often you update this param. Are there other configuration parameters you think should support on-the-fly updates?

Regards,
Mick

**Comment by mickmight** [comment]
Hi @mboyd1 thanks again for raising this. I checked with the team. They confirmed the `minminingtxfee` parameter is not dynamically updated, as you correctly pointed out. This idea can remain on the backlog but it is set with a low priority due to higher priority work the team are currently doing, and the fact that adjustment of this parameter is done irregularly. If the Bitcoin Association feel this is a high priority, they will be able to take this further. Please do feel free to reach out to them. 

Regards,
Mick

**Comment by mboyd1** [comment]
thanks, admittedly in today's transactional economy it is not frequently changed.  generally we run into it when users come to us with transactions that are sitting around unmined for days, because no nodes on the network have a fee requirement low enough to include the transaction.
Typically I have to disable fees entirely, temporarily, by altering minminingtxfee to zero, restart the node, wait for a block to be mined that includes the stuck transaction(s), then set minminingtxfee back to common levels and restart node again
